export default {
  en: {
    title: `The Project`,
    text1: `Soul Mountain is a project that blends music and mountaineering together, two disciplines that at first sight may not seem related at all.`,
    text2: `However, this is not the case for Jordi Mestre(`,
    text21: `), who has always seen a deep connection between the two, creating his most personal project to date thanks to this idea.`,
    text3: `The search for a way to unite these two passions is what brought this Lleida-based musician to create a project that would allow him to play and record his compositions on top of his favourite summits in the Pyrenees.`,
    text4: `Together with mountain guide Roger López de Haro (`,
    text41: `) and cameraman / video producer Jordi Rulló (`,
    text42: `) they form a team that intends to create a series of videos and instrumental songs.`,
    text5: `These creations are always carried out in accordance with the high mountain environment that surrounds the project, trying to raise awareness and emphasizing on nature preservation and culture as two of the basic, necessary pillars for a better future.`,
    text6: `Soul Mountain is a unique, unprecedented project that brings self-composed song recording to summits higher than 3000 metres.`,
    text7: `In this last recording, aranese Singer Alidé Sans and mountain guide Dani Santorens have joined the Soul Mountain team. This is the highest recording to date, climbing up to the Collado Maldito (3200 m.), after crossing the Aneto glacier. All of this has been possible thanks to the sponsorship of the Diputación de Huesca.`,
    text8: `This new video wants to continue raising awareness between our viewers with a clear resounding message: a song to responsibility and hope.`,
    text9: `Thanks to a grant given by Cases de la Música, Soul Mountain have also recorded their first studio album, joined by singers Joana Jové and Alidé Sans. These songs can be downloaded and listened to by donating to the Kilian Jornet Foundation through `,
    text91: `this link`,
    text92: `.`,
  },
  es: {
    title: `El Proyecto`,
    text1: `Soul Mountain es un proyecto que fusiona música y alpinismo, a priori, dos disciplinas que pueden parecer bastante alejadas.`,
    text2: `No obstante, para Jordi Mestre (`,
    text21: `), la música y la montaña siempre han estado íntimamente relacionadas, naciendo de esta idea su proyecto más personal.`,
    text3: `La búsqueda de una forma de unir estas dos grandes pasiones es lo que ha empujado al músico leridano a idear un proyecto que pueda llevarlo a interpretar y grabar su música en sus cimas preferidas de los Pirineos.`,
    text4: `Junto con el guía de montaña Roger López de Haro (`,
    text41: `) y el cámara y productor de vídeo Jordi Rulló (`,
    text42: `) forman un equipo que tiene el objetivo de elaborar una serie de vídeos y canciones instrumentales.`,
    text5: `Estas creaciones siempre se llevan a cabo en acuerdo con el entorno de alta montaña que envuelve el proyecto, intentando concienciar y recalcar la preservación de la naturaleza y la cultura como dos de los pilares básicos necesarios para un futuro mejor.`,
    text6: `Soul Mountain es un proyecto único y sin precedentes que traslada la grabación de música de composición propia a cimas de más de 3000 metros de altura.`,
    text7: `En esta última grabación, la cantante aranesa Alidé Sans y el guía de montaña Dani Santorens se unen al equipo de Soul Mountain. Es la filmación de más altura, subiendo al Collado Maldito (3200 m.), después de cruzar el glaciar del Aneto. Todo esto ha sido posible gracias al patrocinio de la Diputación de Huesca.`,
    text8: `Este nuevo vídeo quiere continuar despertando la conciencia del espectador con un mensaje claro y contundente: un canto a la responsabilidad y la esperanza.`,
    text9: `Gracias a la beca otorgada por Cases de la Música, Soul Mountain también ha grabado su primer disco de estudio con las colaboraciones de las cantantes Joana Jové y Alidé Sans. Los temas se pueden descargar y escuchar haciendo una donación a la Kilian Jornet Foundation a través de `,
    text91: `este enlace`,
    text92: `.`,
  },
  ca: {
    title: `El Projecte`,
    text1: `Soul Mountain és un projecte que fusiona la música i l’alpinisme, a priori, dues disciplines que poden semblar bastant allunyades.`,
    text2: `No obstant això, pel Jordi Mestre (`,
    text21: `) la música i la muntanya sempre han estat íntimament relacionades, i d’aquesta idea neix el seu projecte més personal.`,
    text3: `La recerca d'una forma d'unir aquestes dues grans passions és el que ha empès al músic lleidatà a idear un projecte que pugui portar-lo a interpretar i enregistrar la seva música a dalt dels seus cims preferits del Pirineu.`,
    text4: `Juntament amb el guia Roger López de Haro (`,
    text41: `) i el càmera i productor de vídeo Jordi Rulló (`,
    text42: `) formen un equip que té l’objectiu d’elaborar una sèrie de vídeos i cançons instrumentals.`,
    text5: `Aquestes creacions sempre es duen a terme en acord amb l’entorn d’alta muntanya que envolta el projecte, intentant conscienciar i ressaltar la preservació de la natura i la cultura com dos dels pilars bàsics necessaris per un futur millor.`,
    text6: `Soul Mountain és un projecte únic i sense precedents que trasllada l’enregistrament de música de composició pròpia a cims de més de 3000 metres d’alçada.`,
    text7: `En aquesta última gravació la cantant aranesa Alidé Sans i el guía de muntanya Dani Santorens s’afegeixen a l’equip de Soul Mountain. És la filmació de més alçada, pujant al Collado Maldito (3200 m.), després de creuar la glacera de l’Aneto. Tot això ha sigut possible gràcies al patrocini de la Diputación de Huesca.`,
    text8: `Aquest nou vídeo vol continuar despertat la consciència de l'espectador amb un missatge clar i contundent: un cant a la responsabilitat i esperança.`,
    text9: `Gràcies a la beca atorgada per Cases de la Música, Soul Mountain també ha gravat el seu primer disc d'estudi amb les col·laboracions de les cantants Joana Jové i Alidé Sans. Els temes es poden escoltar i descarregar fent la donació que es vulgui a la Killian Jornet Foundation a través d'`,
    text91: `aquest enllaç`,
    text92: `.`,
  },
};