export default {
    en: {
        title: `The Project`,
        text1: `Soul Mountain is a project that blends music and mountaineering together, two disciplines that at first sight may not seem related at all.`,
        text2: `However, this is not the case for Jordi Mestre(`,
        text21: `), who has always seen a deep connection between the two, creating his most personal project to date thanks to this idea.`,
        text3: `The search for a way to unite these two passions is what brought this Lleida-based musician to create a project that would allow him to play and record his compositions on top of his favourite summits in the Pyrenees.`,
        text4: `Together with mountain guide Roger López de Haro (`,
        text41: `) and cameraman / video producer Jordi Rulló (`,
        text42: `) they form a team that intends to create a series of videos and instrumental songs.`,
        text5: `These creations are always carried out in accordance with the high mountain environment that surrounds the project, trying to raise awareness and emphasizing on nature preservation and culture as two of the basic, necessary pillars for a better future.`,
        text6: `Soul Mountain is a unique, unprecedented project that brings self-composed song recording to summits higher than 3000 metres.`,
        text7: `In their third recording, the team climbed atop Besiberri Nord starting their ascent from the Cavallers dam, in `,
        text71:`. Up there, Jordi Mestre played a new composition entitled “The Change”.`,
        text8: `This latest filming has been done trying to underscore how high mountains are one of the main life sources, as well as the need for action in order to minimize the devastating effects of climate change.`,
        text9: `Thanks to the collaboration with the prestigious company `,
        text91: `, once the third filming of The Soul Mountain has been released, on January 8, 2022, we will start a draw for a `,
        text92: ` Excel Tammany acoustic guitar. All money raised will go entirely to the `,
        text93:`, to fund projects related to preservation of nature in the high mountain environment.`
    },
    es: {
        title: `El Proyecto`,
        text1: `Soul Mountain es un proyecto que fusiona música y alpinismo, a priori, dos disciplinas que pueden parecer bastante alejadas.`,
        text2: `No obstante, para Jordi Mestre (`,
        text21: `), la música y la montaña siempre han estado íntimamente relacionadas, naciendo de esta idea su proyecto más personal.`,
        text3: `La búsqueda de una forma de unir estas dos grandes pasiones es lo que ha empujado al músico leridano a idear un proyecto que pueda llevarlo a interpretar y grabar su música en sus cimas preferidas de los Pirineos.`,
        text4: `Junto con el guía de montaña Roger López de Haro (`,
        text41: `) y el cámara y productor de vídeo Jordi Rulló (`,
        text42: `) forman un equipo que tiene el objetivo de elaborar una serie de vídeos y canciones instrumentales.`,
        text5: `Estas creaciones siempre se llevan a cabo en acuerdo con el entorno de alta montaña que envuelve el proyecto, intentando concienciar y recalcar la preservación de la naturaleza y la cultura como dos de los pilares básicos necesarios para un futuro mejor.`,
        text6: `Soul Mountain es un proyecto único y sin precedentes que traslada la grabación de música de composición propia a cimas de más de 3000 metros de altura.`,
        text7: `En su tercera grabación, el equipo ha escalado la cima del Besiberri Nord, iniciando el ascenso desde la presa de Cavallers, en el `,
        text71: `. Una vez arriba, Jordi Mestre ha interpretado una nueva composición titulada “The Change”.`,
        text8: `Con esta nueva filmación se pretende poner en valor la alta montaña como una de las principales fuentes de vida, así como la necesidad de actuar para minimizar los efectos devastadores del cambio climático.`,
        text9: `Gracias a la colaboración con la prestigiosa empresa `,
        text91: `, una vez estrenada la tercera entrega de The Soul Mountain, el día 8 de enero de 2022, iniciaremos un sorteo de una guitarra acústica `,
        text92: ` Excel Tammany. Todo el dinero recaudado irá destinado íntegramente a la `,
        text93:`, para financiar proyectos relacionados con la preservación del medio natural en el entorno de la alta montaña.`
    },
    ca: {
        title: `El Projecte`,
        text1: `Soul Mountain és un projecte que fusiona la música i l’alpinisme, a priori, dues disciplines que poden semblar bastant allunyades.`,
        text2: `No obstant això, pel Jordi Mestre (`,
        text21: `) la música i la muntanya sempre han estat íntimament relacionades, i d’aquesta idea neix el seu projecte més personal.`,
        text3: `La recerca d'una forma d'unir aquestes dues grans passions és el que ha empès al músic lleidatà a idear un projecte que pugui portar-lo a interpretar i enregistrar la seva música a dalt dels seus cims preferits del Pirineu.`,
        text4: `Juntament amb el guia Roger López de Haro (`,
        text41: `) i el càmera i productor de vídeo Jordi Rulló (`,
        text42: `) formen un equip que té l’objectiu d’elaborar una sèrie de vídeos i cançons instrumentals.`,
        text5: `Aquestes creacions sempre es duen a terme en acord amb l’entorn d’alta muntanya que envolta el projecte, intentant conscienciar i ressaltar la preservació de la natura i la cultura com dos dels pilars bàsics necessaris per un futur millor.`,
        text6: `Soul Mountain és un projecte únic i sense precedents que trasllada l’enregistrament de música de composició pròpia a cims de més de 3000 metres d’alçada.`,
        text7: `En la seva tercera gravació, l’equip ha escalat el cim del Besiberri Nord iniciant l’ascens des de la presa de Cavallers, a la `,
        text71: `. Un cop a dalt, el Jordi Mestre ha interpretat una nova composició titulada “The Change”.`,
        text8: `Amb aquesta nova filmació es pretén posar en valor l’alta muntanya com una de les principals fonts de vida, així com la necessitat d’actuar per minimitzar els efectes devastadors del canvi climàtic.`,
        text9:`Gràcies a la col·laboració amb la prestigiosa empresa `,
        text91:`, un cop estrenada la tercera entrega de The Soul Mountain, el dia 8 de gener de 2022, iniciarem un sorteig d'una guitarra acústica `,
        text92: ` Excel Tammany. Tots els diners recaptats aniran destinats íntegrament a la `,
        text93:`, per finançar projectes relacionats amb la preservació del medi natural en l'entorn de l'alta muntanya.`

    }
}